const CATS=["Foundations","Candlestick","Identity","Psychology","Institutional","Live"];
const LESSONS=[
{id:0,cat:"Foundations",title:"Welcome: Before We Begin",body:[
{h:"📘 WELCOME TO THE FOREX TRADING ACADEMY: BEFORE WE BEGIN",p:[]},
{h:"⚠️ THE REALITY OF RISK",p:["Trading foreign exchange carries substantial risk. This platform provides educational content only. It does not offer financial advice, manage your capital, or guarantee profits. According to industry data, 70% to 80% of retail trading accounts lose money. The market does not care about your predictions, your timeline, or your expectations. It only rewards discipline, preparation, and strict risk management.","You can lose your entire trading balance if you ignore stop losses, overleverage, revenge trade, or operate without a written plan. Past performance never guarantees future results. Volatility, spread widening, slippage, and unexpected news can erase accounts in minutes. Treat every dollar you risk like it is the last one. Protect your capital first. Let profits follow as a byproduct of consistency."]},
{h:"📓 THE NON-NEGOTIABLE JOURNAL",p:["If you take nothing else from this academy, make it this: your trading journal is your edge.","Without a journal, you are trading blind. You will repeat the same mistakes, forget what actually works, and let emotions override your plan. A proper journal records every single trade: your setup, entry/exit, risk size, emotional state, and outcome. Over time, it reveals your true win rate, exposes psychological leaks, and transforms random speculation into a repeatable business system.","You will be provided a structured journal to log every practice and live trade. Use it daily. Review it weekly. If you are not tracking your execution, you are not trading professionally."]},
{h:"✅ YOUR COMMITMENT",p:["By proceeding, you acknowledge that:\n1. Trading involves real financial risk and potential loss of capital.\n2. This academy is for educational purposes only and does not provide investment advice.\n3. You accept full responsibility for your trades, risk management, and results.\n4. You commit to using the provided journal, following the curriculum step-by-step, and treating trading as a disciplined skill, not a lottery.","If you understand the risk, respect the process, and are ready to build a sustainable edge, let's get to work. 💡📈"]}],
quiz:[
{q:"What percentage of retail trading accounts are estimated to lose money?",o:["10% to 20%","30% to 40%","50% to 60%","70% to 80%"],a:3},
{q:"Why is the trading journal considered your 'edge'?",o:["It guarantees future profits","It transforms speculation into a repeatable business system","It predicts exact market movements","It provides financial advice"],a:1}]},
{id:1,cat:"Foundations",title:"LESSON 1: What is Forex Trading",body:[
{h:"",p:["Forex trading explained simply means buying and selling currencies to profit from price changes. The foreign exchange market is the largest and most liquid financial market in the world, where trillions of dollars change hands every single day. Unlike traditional stock markets that operate on centralized exchanges, forex trading works as a fully decentralized network. Banks, governments, hedge funds, and retail traders are connected electronically, allowing currency exchange to happen instantly across the globe. This unique structure keeps the market open twenty-four hours a day, five days a week.","Trading follows the sun as major financial centers open and close, starting in Sydney and Tokyo, moving to London, and finishing in New York. Understanding forex trading for beginners starts with recognizing that every transaction involves swapping one currency for another. When you trade, you are essentially betting on whether one currency will strengthen or weaken against another. Success in this market does not come from guessing; it comes from learning market mechanics, reading price action, and practicing strict risk management.","Many newcomers search for forex basics because the market moves quickly and demands emotional control. Impulsive decisions and a lack of planning drain accounts faster than unpredictable price swings. The most reliable path forward involves observing how economic reports, central bank policies, and global events shift currency values. Watch how prices form clear trends, enter consolidation phases, and eventually reverse. Practice consistently in a demo environment until your entry and exit rules become automatic. The market never rewards impatience; it only rewards discipline, preparation, and repetition. Build a daily routine of reviewing charts, journaling observations, and testing strategies with virtual capital before risking real funds. Consistent education and structured practice will always outperform quick shortcuts."]}],
quiz:[
{q:"What makes the forex market unique compared to traditional stock markets?",o:["It runs on a single centralized exchange","It operates 24/5 as a decentralized global network","It only allows institutional investors to trade","It requires physical delivery of currency"],a:1},
{q:"What is the most important foundation for beginner forex trading success?",o:["Predicting every short-term price move","Discipline, structured practice, and risk management","Using the highest possible leverage ratio","Trading exclusively during major news releases"],a:1},
{q:"Why is practicing in a demo account highly recommended for beginners?",o:["It guarantees future profits in the live market","It allows traders to test strategies without financial risk","It removes the need to learn risk management","It automatically adjusts broker spreads to zero"],a:1}]},
{id:2,cat:"Foundations",title:"LESSON 2: Currency Pairs Explained",body:[
{h:"📌 PASTE YOUR REAL LESSON 2 TEXT HERE",p:["Placeholder so you see the pattern. In Acode, replace this paragraph with your real Lesson 2 content and write quiz questions exactly like Lessons 0 and 1. That's the whole system — repeat for all 66 lessons."]}],
quiz:[
{q:"Placeholder check: what do you replace in this lesson?",o:["Nothing","The body text and quiz with my real content","The whole app","My phone"],a:1}]}
];